from __future__ import annotations


# Verified against FotMob's current 2026/27 (calendar leagues: 2026) tables.
# Each row is: local lottery name, FotMob team id, accepted provider/Chinese aliases.
LEAGUE_TEAM_ROWS: dict[str, tuple[tuple[str, int, tuple[str, ...]], ...]] = {
    "英超": (
        ("伯恩茅斯", 8678, ("AFC Bournemouth", "Bournemouth")),
        ("阿森纳", 9825, ("Arsenal",)),
        ("阿斯顿维拉", 10252, ("Aston Villa", "维拉")),
        ("布伦特福德", 9937, ("Brentford",)),
        ("布赖顿", 10204, ("Brighton & Hove Albion", "Brighton", "布莱顿")),
        ("切尔西", 8455, ("Chelsea",)),
        ("考文垂", 8669, ("Coventry City", "Coventry", "考文垂城")),
        ("水晶宫", 9826, ("Crystal Palace",)),
        ("埃弗顿", 8668, ("Everton",)),
        ("富勒姆", 9879, ("Fulham",)),
        ("赫尔城", 8667, ("Hull City", "Hull")),
        ("伊普斯维奇", 9902, ("Ipswich Town", "Ipswich")),
        ("利兹联", 8463, ("Leeds United", "Leeds")),
        ("利物浦", 8650, ("Liverpool",)),
        ("曼城", 8456, ("Manchester City", "Man City")),
        ("曼联", 10260, ("Manchester United", "Man United")),
        ("纽卡斯尔", 10261, ("Newcastle United", "Newcastle", "纽卡斯尔联")),
        ("诺丁汉森林", 10203, ("Nottingham Forest", "Nottm Forest", "诺丁汉")),
        ("桑德兰", 8472, ("Sunderland",)),
        ("热刺", 8586, ("Tottenham Hotspur", "Tottenham", "Spurs")),
    ),
    "德甲": (
        ("科隆", 8722, ("1. FC Köln", "FC Köln", "Köln", "Cologne")),
        ("奥格斯堡", 8406, ("Augsburg", "FC Augsburg")),
        ("勒沃库森", 8178, ("Bayer Leverkusen", "Leverkusen")),
        ("拜仁", 9823, ("Bayern München", "Bayern Munich", "拜仁慕尼黑")),
        ("多特蒙德", 9789, ("Borussia Dortmund", "Dortmund")),
        ("门兴", 9788, ("Borussia Mönchengladbach", "Borussia Monchengladbach", "M'gladbach", "门兴格拉德巴赫")),
        ("法兰克福", 9810, ("Eintracht Frankfurt", "Frankfurt")),
        ("埃尔沃斯堡", 8232, ("Elversberg", "SV Elversberg", "艾禾斯堡", "埃弗斯堡")),
        ("弗赖堡", 8358, ("Freiburg", "SC Freiburg")),
        ("汉堡", 9790, ("Hamburger SV", "Hamburg")),
        ("霍芬海姆", 8226, ("Hoffenheim", "TSG Hoffenheim")),
        ("美因茨", 9905, ("Mainz 05", "Mainz")),
        ("帕德博恩", 8460, ("Paderborn", "SC Paderborn")),
        ("莱比锡", 178475, ("RB Leipzig", "Leipzig", "莱比锡红牛")),
        ("沙尔克", 10189, ("Schalke 04", "Schalke")),
        ("柏林联合", 8149, ("Union Berlin", "1. FC Union Berlin")),
        ("斯图加特", 10269, ("VfB Stuttgart", "Stuttgart")),
        ("不莱梅", 8697, ("Werder Bremen", "Bremen", "云达不莱梅")),
    ),
    "意甲": (
        ("亚特兰大", 8524, ("Atalanta",)),
        ("博洛尼亚", 9857, ("Bologna",)),
        ("卡利亚里", 8529, ("Cagliari",)),
        ("科莫", 10171, ("Como",)),
        ("佛罗伦萨", 8535, ("Fiorentina",)),
        ("弗罗西诺内", 9891, ("Frosinone", "佛罗西诺内")),
        ("热那亚", 10233, ("Genoa",)),
        ("国际米兰", 8636, ("Inter", "Inter Milan", "国米")),
        ("尤文图斯", 9885, ("Juventus", "尤文")),
        ("拉齐奥", 8543, ("Lazio",)),
        ("莱切", 9888, ("Lecce",)),
        ("AC米兰", 8564, ("Milan", "AC Milan")),
        ("蒙扎", 6504, ("Monza",)),
        ("那不勒斯", 9875, ("Napoli",)),
        ("帕尔马", 10167, ("Parma",)),
        ("罗马", 8686, ("Roma", "AS Roma")),
        ("萨索洛", 7943, ("Sassuolo",)),
        ("都灵", 9804, ("Torino",)),
        ("乌迪内斯", 8600, ("Udinese",)),
        ("威尼斯", 7881, ("Venezia",)),
    ),
    "西甲": (
        ("毕尔巴鄂", 8315, ("Athletic Club", "Athletic Bilbao", "毕尔巴鄂竞技")),
        ("马竞", 9906, ("Atlético Madrid", "Atletico Madrid", "马德里竞技")),
        ("巴萨", 8634, ("Barcelona", "FC Barcelona", "巴塞罗那")),
        ("塞尔塔", 9910, ("Celta Vigo", "Celta")),
        ("拉科鲁尼亚", 9783, ("Deportivo A Coruña", "Deportivo La Coruna", "Deportivo")),
        ("阿拉维斯", 9866, ("Deportivo Alavés", "Deportivo Alaves", "Alavés", "Alaves")),
        ("埃尔切", 10268, ("Elche",)),
        ("西班牙人", 8558, ("Espanyol",)),
        ("赫塔费", 8305, ("Getafe",)),
        ("莱万特", 8581, ("Levante",)),
        ("马拉加", 9864, ("Málaga", "Malaga")),
        ("奥萨苏纳", 8371, ("Osasuna",)),
        ("桑坦德", 8696, ("Racing Santander", "Racing de Santander", "桑坦德竞技")),
        ("巴列卡诺", 8370, ("Rayo Vallecano", "Rayo")),
        ("贝蒂斯", 8603, ("Real Betis", "Betis", "皇家贝蒂斯")),
        ("皇马", 8633, ("Real Madrid", "皇家马德里")),
        ("皇家社会", 8560, ("Real Sociedad",)),
        ("塞维利亚", 8302, ("Sevilla",)),
        ("巴伦西亚", 10267, ("Valencia", "瓦伦西亚")),
        ("比利亚雷亚尔", 10205, ("Villarreal",)),
    ),
    "法甲": (
        ("昂热", 8121, ("Angers",)),
        ("欧塞尔", 8583, ("Auxerre",)),
        ("布雷斯特", 8521, ("Brest",)),
        ("勒阿弗尔", 9746, ("Le Havre",)),
        ("勒芒", 8682, ("Le Mans",)),
        ("朗斯", 8588, ("Lens",)),
        ("里尔", 8639, ("Lille",)),
        ("洛里昂", 8689, ("Lorient",)),
        ("里昂", 9748, ("Lyon",)),
        ("马赛", 8592, ("Marseille", "Olympique Marseille")),
        ("摩纳哥", 9829, ("Monaco", "AS Monaco")),
        ("尼斯", 9831, ("Nice",)),
        ("巴黎FC", 6379, ("Paris FC", "巴黎足球会")),
        ("巴黎圣日耳曼", 9847, ("Paris Saint-Germain", "Paris SG", "PSG", "巴黎", "巴黎圣曼")),
        ("雷恩", 9851, ("Rennes", "Stade Rennais")),
        ("斯特拉斯堡", 9848, ("Strasbourg",)),
        ("图卢兹", 9941, ("Toulouse",)),
        ("特鲁瓦", 10242, ("Troyes",)),
    ),
    "荷甲": (
        ("海牙", 10217, ("ADO Den Haag", "Den Haag")),
        ("阿贾克斯", 8593, ("Ajax",)),
        ("阿尔克马尔", 10229, ("AZ Alkmaar", "AZ")),
        ("坎布尔", 7788, ("Cambuur", "SC Cambuur")),
        ("鹿特丹精英", 10218, ("Excelsior", "SBV Excelsior", "精英")),
        ("格罗宁根", 8674, ("FC Groningen", "Groningen")),
        ("特温特", 8611, ("FC Twente", "Twente")),
        ("乌得勒支", 9908, ("FC Utrecht", "Utrecht")),
        ("费耶诺德", 10235, ("Feyenoord",)),
        ("福图纳", 6422, ("Fortuna Sittard", "福图纳锡塔德")),
        ("前进之鹰", 6433, ("Go Ahead Eagles",)),
        ("奈梅亨", 8464, ("NEC Nijmegen", "NEC")),
        ("兹沃勒", 6413, ("PEC Zwolle", "Zwolle")),
        ("埃因霍温", 8640, ("PSV Eindhoven", "PSV")),
        ("海伦芬", 10228, ("SC Heerenveen", "Heerenveen")),
        ("鹿特丹斯巴达", 8614, ("Sparta Rotterdam",)),
        ("特尔斯达", 6414, ("Telstar",)),
        ("威廉二世", 8525, ("Willem II",)),
    ),
    "葡超": (
        ("维塞乌", 1786, ("Académico Viseu", "Academico Viseu")),
        ("阿尔韦卡", 9780, ("Alverca", "FC Alverca")),
        ("阿罗卡", 158085, ("Arouca",)),
        ("本菲卡", 9772, ("Benfica",)),
        ("布拉加", 10264, ("Braga", "Sporting Braga")),
        ("卡萨皮亚", 212821, ("Casa Pia AC", "Casa Pia")),
        ("埃斯托里尔", 7842, ("Estoril",)),
        ("阿马多拉之星", 1074320, ("Estrela da Amadora", "Estrela Amadora")),
        ("法马利康", 1634, ("Famalicão", "Famalicao")),
        ("波尔图", 9773, ("FC Porto", "Porto")),
        ("吉维森特", 9764, ("Gil Vicente",)),
        ("马里迪莫", 10212, ("Marítimo", "Maritimo")),
        ("莫雷拉人", 8348, ("Moreirense",)),
        ("葡萄牙国民", 10214, ("Nacional", "CD Nacional", "国民队")),
        ("里奥阿维", 7841, ("Rio Ave",)),
        ("圣克拉拉", 1567, ("Santa Clara",)),
        ("葡萄牙体育", 9768, ("Sporting CP", "Sporting Lisbon", "里斯本竞技")),
        ("吉马良斯", 7844, ("Vitória de Guimarães", "Vitoria de Guimaraes", "Vitoria Guimaraes")),
    ),
    "法乙": (
        ("阿讷西", 293352, ("Annecy FC", "Annecy")),
        ("布洛涅", 4170, ("Boulogne",)),
        ("克莱蒙", 8311, ("Clermont Foot", "Clermont")),
        ("第戎", 9836, ("Dijon",)),
        ("敦刻尔克", 47214, ("Dunkerque",)),
        ("格勒诺布尔", 9855, ("Grenoble",)),
        ("甘冈", 9747, ("Guingamp",)),
        ("拉瓦勒", 7853, ("Laval",)),
        ("梅斯", 8550, ("Metz",)),
        ("蒙彼利埃", 10249, ("Montpellier",)),
        ("南锡", 8481, ("Nancy",)),
        ("南特", 9830, ("Nantes",)),
        ("波城", 6355, ("Pau",)),
        ("红星", 6390, ("Red Star", "Red Star FC")),
        ("兰斯", 9837, ("Reims",)),
        ("罗德兹", 4120, ("Rodez",)),
        ("圣埃蒂安", 9853, ("Saint-Étienne", "Saint-Etienne")),
        ("索肖", 9874, ("Sochaux",)),
    ),
    "瑞典超": (
        ("索尔纳", 8349, ("AIK", "AIK Solna")),
        ("布鲁马波卡纳", 8501, ("Brommapojkarna", "IF Brommapojkarna")),
        ("代格福什", 6544, ("Degerfors",)),
        ("尤尔加登", 9802, ("Djurgården", "Djurgarden", "佐加顿斯")),
        ("埃尔夫斯堡", 8014, ("Elfsborg",)),
        ("盖斯", 8297, ("GAIS", "哥德堡盖斯")),
        ("赫根", 8428, ("Häcken", "Hacken", "BK Häcken")),
        ("哈尔姆斯塔德", 8310, ("Halmstads BK", "Halmstad")),
        ("哈马比", 8248, ("Hammarby",)),
        ("哥德堡", 9893, ("IFK Göteborg", "IFK Goteborg")),
        ("卡尔马", 9892, ("Kalmar FF", "Kalmar")),
        ("马尔默", 10237, ("Malmö FF", "Malmo FF", "Malmö")),
        ("米亚尔比", 8127, ("Mjällby", "Mjallby")),
        ("奥尔格里特", 10002, ("Örgryte", "Orgryte")),
        ("天狼星", 6694, ("Sirius", "IK Sirius")),
        ("韦斯特罗斯", 6194, ("Västerås SK", "Vasteras SK")),
    ),
    "芬超": (
        ("奥卢", 4449, ("AC Oulu", "Oulu")),
        ("图尔库国际", 6550, ("FC Inter Turku", "Inter Turku")),
        ("拉赫蒂", 8424, ("FC Lahti", "Lahti")),
        ("查路", 8473, ("FF Jaro", "Jaro")),
        ("赫尔辛基", 9861, ("HJK", "HJK Helsinki")),
        ("格尼斯坦", 2361, ("IF Gnistan", "Gnistan")),
        ("玛丽港", 6634, ("IFK Mariehamn", "Mariehamn")),
        ("埃尔维斯", 162146, ("Ilves",)),
        ("古比斯", 1693, ("KuPS", "KuPS Kuopio", "库奥皮奥")),
        ("塞那乔其", 162162, ("SJK", "Seinäjoen JK", "Seinajoen JK")),
        ("TPS图尔库", 6633, ("TPS", "TPS Turku")),
        ("瓦萨", 6597, ("VPS", "VPS Vaasa")),
    ),
    "瑞士超": (
        ("巴塞尔", 9931, ("Basel", "FC Basel")),
        ("瓦杜兹", 9824, ("FC Vaduz", "Vaduz")),
        ("苏黎世", 10243, ("FC Zürich", "FC Zurich", "Zürich")),
        ("草蜢", 9956, ("Grasshopper", "Grasshopper Club Zürich", "Grasshoppers")),
        ("洛桑", 7730, ("Lausanne", "Lausanne-Sport")),
        ("卢加诺", 7896, ("Lugano", "FC Lugano")),
        ("卢塞恩", 10199, ("Luzern", "FC Luzern")),
        ("塞尔维特", 9777, ("Servette",)),
        ("锡永", 10179, ("Sion", "FC Sion")),
        ("圣加仑", 10190, ("St. Gallen", "St Gallen")),
        ("图恩", 10191, ("Thun", "FC Thun")),
        ("年轻人", 10192, ("Young Boys", "BSC Young Boys")),
    ),
    "美职": (
        ("亚特兰大联", 773958, ("Atlanta United",)),
        ("奥斯汀FC", 1218886, ("Austin FC", "奥斯汀")),
        ("蒙特利尔", 161195, ("CF Montréal", "CF Montreal", "Montreal Impact")),
        ("夏洛特FC", 1323940, ("Charlotte FC", "夏洛特")),
        ("芝加哥火焰", 6397, ("Chicago Fire FC", "Chicago Fire")),
        ("科罗拉多急流", 8314, ("Colorado Rapids",)),
        ("哥伦布机员", 6001, ("Columbus Crew", "Columbus")),
        ("华盛顿联", 6602, ("DC United", "D.C. United")),
        ("辛辛那提", 722265, ("FC Cincinnati", "Cincinnati")),
        ("达拉斯FC", 6399, ("FC Dallas", "Dallas")),
        ("休斯敦迪纳摩", 8259, ("Houston Dynamo FC", "Houston Dynamo")),
        ("迈阿密国际", 960720, ("Inter Miami CF", "Inter Miami")),
        ("洛杉矶银河", 6637, ("LA Galaxy", "Los Angeles Galaxy")),
        ("洛杉矶FC", 867280, ("Los Angeles FC", "LAFC")),
        ("明尼苏达联", 207242, ("Minnesota United",)),
        ("纳什维尔", 915807, ("Nashville SC", "Nashville")),
        ("新英格兰", 6580, ("New England Revolution", "New England")),
        ("纽约城", 546238, ("New York City FC", "NYCFC")),
        ("奥兰多城", 267810, ("Orlando City",)),
        ("费城联合", 191716, ("Philadelphia Union", "Philadelphia")),
        ("波特兰伐木者", 307690, ("Portland Timbers", "Portland")),
        ("皇家盐湖城", 6606, ("Real Salt Lake", "Salt Lake")),
        ("纽约红牛", 6514, ("Red Bull New York", "New York Red Bulls", "NY Red Bulls")),
        ("圣迭戈FC", 1701119, ("San Diego FC", "圣迭戈")),
        ("圣何塞地震", 6603, ("San Jose Earthquakes", "San Jose")),
        ("西雅图海湾人", 130394, ("Seattle Sounders FC", "Seattle Sounders")),
        ("堪萨斯城竞技", 6604, ("Sporting Kansas City", "Sporting KC")),
        ("圣路易斯城", 1427963, ("St. Louis City", "St Louis City", "St. Louis City SC")),
        ("多伦多FC", 56453, ("Toronto FC", "Toronto")),
        ("温哥华白浪", 307691, ("Vancouver Whitecaps", "Vancouver Whitecaps FC", "Vancouver")),
    ),
}


# UEFA's verified 2026/27 league-phase participants.  These rosters are kept
# separately from the domestic league tables because a cup roster is a
# season-specific identity source, not a domestic competition table.  Repeated
# clubs are merged into the same canonical identity below.
EUROPEAN_CUP_TEAM_ROWS: dict[str, tuple[tuple[str, int, tuple[str, ...]], ...]] = {
    "欧冠": (
        ("雅典AEK", 8563, ("AEK Athens", "AEK雅典")),
        ("阿森纳", 9825, ("Arsenal",)),
        ("阿斯顿维拉", 10252, ("Aston Villa", "维拉")),
        ("马竞", 9906, ("Atlético Madrid", "Atletico Madrid", "Atleti", "马德里竞技")),
        ("巴萨", 8634, ("Barcelona", "FC Barcelona", "巴塞罗那")),
        ("拜仁", 9823, ("Bayern München", "Bayern Munich", "拜仁慕尼黑")),
        ("博德闪耀", 8402, ("Bodø/Glimt", "Bodo/Glimt", "Bodo Glimt", "博德")),
        ("多特蒙德", 9789, ("Borussia Dortmund", "Dortmund")),
        ("布鲁日", 8342, ("Club Brugge", "Club Brugge KV", "布鲁日俱乐部")),
        ("科莫", 10171, ("Como",)),
        ("费内巴切", 8695, ("Fenerbahçe", "Fenerbahce")),
        ("费耶诺德", 10235, ("Feyenoord",)),
        ("加拉塔萨雷", 8637, ("Galatasaray", "加拉塔萨")),
        ("国际米兰", 8636, ("Inter", "Inter Milan", "国米")),
        ("林茨", 9977, ("LASK", "LASK Linz", "Linz ASK")),
        ("莱比锡", 178475, ("RB Leipzig", "Leipzig", "莱比锡红牛", "莱红牛")),
        ("朗斯", 8588, ("Lens", "RC Lens")),
        ("里尔", 8639, ("Lille", "LOSC Lille")),
        ("利物浦", 8650, ("Liverpool",)),
        ("曼城", 8456, ("Manchester City", "Man City")),
        ("曼联", 10260, ("Manchester United", "Man United")),
        ("那不勒斯", 9875, ("Napoli",)),
        ("巴黎圣日耳曼", 9847, ("Paris Saint-Germain", "Paris SG", "PSG", "巴黎", "巴黎圣曼")),
        ("波尔图", 9773, ("FC Porto", "Porto")),
        ("埃因霍温", 8640, ("PSV Eindhoven", "PSV")),
        ("贝蒂斯", 8603, ("Real Betis", "Betis", "皇家贝蒂斯")),
        ("皇马", 8633, ("Real Madrid", "皇家马德里")),
        ("罗马", 8686, ("Roma", "AS Roma")),
        ("萨巴赫", 951893, ("Sabah", "Sabah FK", "沙巴巴库")),
        ("顿涅茨克矿工", 9728, ("Shakhtar Donetsk", "Shakhtar", "矿工")),
        ("布拉格斯拉维亚", 7787, ("Slavia Prague", "Slavia Praha", "斯拉维亚")),
        ("布拉迪斯拉发", 6019, ("Slovan Bratislava", "S. Bratislava", "斯洛万布拉迪斯拉发")),
        ("葡萄牙体育", 9768, ("Sporting CP", "Sporting Lisbon", "里斯本竞技")),
        ("斯图加特", 10269, ("VfB Stuttgart", "Stuttgart")),
        ("维京", 8478, ("Viking", "Viking FK")),
        ("比利亚雷亚尔", 10205, ("Villarreal",)),
    ),
    "欧联": (
        ("安德莱赫特", 8635, ("Anderlecht", "RSC Anderlecht")),
        ("阿拉拉特亚美尼亚", 866109, ("Ararat-Armenia", "Ararat Armenia", "FC Ararat-Armenia")),
        ("阿尔克马尔", 10229, ("AZ Alkmaar", "AZ")),
        ("本菲卡", 9772, ("Benfica", "SL Benfica")),
        ("贝西克塔斯", 10188, ("Beşiktaş", "Besiktas")),
        ("伯恩茅斯", 8678, ("AFC Bournemouth", "Bournemouth")),
        ("塞尔塔", 9910, ("Celta Vigo", "Celta")),
        ("凯尔特人", 9925, ("Celtic", "Celtic FC")),
        ("采列", 4622, ("NK Celje", "Celje")),
        ("水晶宫", 9826, ("Crystal Palace",)),
        ("萨格勒布迪纳摩", 10156, ("Dinamo Zagreb", "GNK Dinamo", "GNK Dinamo Zagreb")),
        ("费伦茨瓦罗斯", 8222, ("Ferencváros", "Ferencvaros", "Ferencvárosi TC", "费伦茨")),
        ("贝尔谢巴工人", 9754, ("Hapoel Beer Sheva", "Hapoel Be'er Sheva", "H. Beer-Sheva")),
        ("霍芬海姆", 8226, ("Hoffenheim", "TSG Hoffenheim")),
        ("乔治罗尼亚", 1957, ("Jagiellonia Białystok", "Jagiellonia Bialystok", "Jagiellonia")),
        ("尤文图斯", 9885, ("Juventus", "尤文")),
        ("勒沃库森", 8178, ("Bayer Leverkusen", "Leverkusen")),
        ("波兹南莱赫", 2182, ("Lech Poznań", "Lech Poznan", "Lech")),
        ("索菲亚列夫斯基", 8632, ("Levski Sofia", "PFC Levski Sofia")),
        ("利勒斯特罗姆", 8476, ("Lillestrøm", "Lillestrom", "Lillestrøm SK", "利勒斯")),
        ("里昂", 9748, ("Lyon", "Olympique Lyonnais")),
        ("AC米兰", 8564, ("Milan", "AC Milan")),
        ("马赛", 8592, ("Marseille", "Olympique Marseille", "Olympique de Marseille")),
        ("奈梅亨", 8464, ("NEC Nijmegen", "NEC", "N.E.C.")),
        ("克里特", 7753, ("OFI Crete", "OFI", "OFI Crete FC", "克里特OFI")),
        ("奥林匹亚科斯", 8638, ("Olympiacos", "Olympiakos")),
        ("奥莫尼亚", 8044, ("Omonia Nicosia", "Omonia", "AC Omonia")),
        ("雷恩", 9851, ("Rennes", "Stade Rennais")),
        ("萨尔茨堡", 10013, ("Salzburg", "Red Bull Salzburg", "RB Salzburg")),
        ("布拉格斯巴达", 10247, ("Sparta Prague", "Sparta Praha", "AC Sparta Praha")),
        ("格拉茨风暴", 10014, ("Sturm Graz", "SK Sturm Graz")),
        ("桑德兰", 8472, ("Sunderland",)),
        ("托伦斯", 212820, ("Torreense", "SCU Torreense", "S.C.U. Torreense")),
        ("圣吉罗斯联合", 7978, ("Union St.Gilloise", "Union Saint-Gilloise", "Union SG", "圣吉罗斯")),
        ("比尔森胜利", 6033, ("Viktoria Plzeň", "Viktoria Plzen", "比尔森")),
        ("皇家社会", 8560, ("Real Sociedad",)),
    ),
    "欧协联": (
        ("奥胡斯", 8071, ("AGF", "Aarhus", "AGF Aarhus")),
        ("阿贾克斯", 8593, ("Ajax",)),
        ("亚特兰大", 8524, ("Atalanta",)),
        ("巴尼亚卢卡战士", 10116, ("Borac Banja Luka", "Borac", "FK Borac Banja Luka")),
        ("布拉加", 10264, ("Braga", "Sporting Braga")),
        ("布兰", 8468, ("Brann", "SK Brann")),
        ("布赖顿", 10204, ("Brighton & Hove Albion", "Brighton", "布莱顿")),
        ("哥本哈根", 8391, ("FC København", "FC Copenhagen", "Copenhagen")),
        ("贝尔格莱德红星", 8687, ("FK Crvena Zvezda", "Crvena Zvezda", "Red Star Belgrade", "红星")),
        ("索菲亚中央陆军", 10144, ("CSKA Sofia", "PFC CSKA Sofia")),
        ("埃格纳蒂亚", 10039, ("Egnatia", "KF Egnatia")),
        ("弗赖堡", 8358, ("Freiburg", "SC Freiburg")),
        ("根特", 9991, ("Gent", "KAA Gent")),
        ("赫塔费", 8305, ("Getafe", "赫塔菲")),
        ("哈伊杜克", 10154, ("Hajduk Split", "HNK Hajduk Split")),
        ("哈茨", 9860, ("Heart of Midlothian", "Hearts")),
        ("第比利斯伊比利亚", 480291, ("Iberia Tbilisi", "Iberia 1999", "FC Iberia 1999", "萨布塔洛")),
        ("伊斯卡尔德斯国际", 10050, ("Inter Club d'Escaldes", "Inter Escaldes")),
        ("亚布洛内茨", 7758, ("Jablonec", "FK Jablonec")),
        ("阿拉木图凯拉特", 8037, ("Kairat Almaty", "Kairat", "阿拉木图")),
        ("考纳斯萨尔基利斯", 439132, ("FK Kauno Žalgiris", "Kauno Žalgiris", "Kauno Zalgiris")),
        ("古比斯", 1693, ("KuPS", "KuPS Kuopio", "库奥皮奥")),
        ("林肯红魔", 545012, ("Lincoln Red Imps FC", "Lincoln Red Imps", "L. Red Imps")),
        ("卢加诺", 7896, ("Lugano", "FC Lugano")),
        ("中日德兰", 8113, ("FC Midtjylland", "Midtjylland")),
        ("米亚尔比", 8127, ("Mjällby", "Mjallby", "Mjällby AIF")),
        ("摩纳哥", 9829, ("Monaco", "AS Monaco")),
        ("北西兰", 10202, ("Nordsjælland", "Nordsjaelland", "FC Nordsjælland")),
        ("帕福斯FC", 2137, ("Pafos FC", "Pafos", "帕福斯")),
        ("帕纳辛奈科斯", 10200, ("Panathinaikos", "Panathinaikos FC")),
        ("里加FC", 624924, ("Riga FC", "Riga", "里加")),
        ("圣图尔登", 9997, ("St.Truiden", "Sint-Truidense", "Sint-Truiden")),
        ("图恩", 10191, ("Thun", "FC Thun")),
        ("特拉布宗体育", 9752, ("Trabzonspor",)),
        ("特温特", 8611, ("FC Twente", "Twente")),
        ("克拉约瓦大学", 480286, ("Universitatea Craiova", "U. Craiova", "CS Universitatea Craiova")),
    ),
}


# AFC's verified 2026/27 league/group-stage participants.  Keep the Elite and
# Two rosters separate so an identity match can also use the competition tier
# as context.  The IDs and provider spellings come from FotMob's opening-round
# fixtures after the AFC draws were finalised.
ASIAN_CUP_TEAM_ROWS: dict[str, tuple[tuple[str, int, tuple[str, ...]], ...]] = {
    "亚冠精英": (
        ("费尔干纳石油", 102145, ("Neftchi Fargona", "Neftchi Fergana", "费尔干纳")),
        ("巴格达空军", 101656, ("Al Quwa Al Jawiya", "Air Force Club")),
        ("舒马尔", 101904, ("Al-Shamal", "Al Shamal")),
        ("吉达联合", 8577, ("Al Ittihad", "Al-Ittihad Club", "Ittihad Jeddah")),
        ("迪拜青年国民", 102119, ("Shabab Al-Ahli Dubai FC", "Shabab Al Ahli", "迪拜国民")),
        ("大不里士拖拉机", 176352, ("Tractor", "Tractor FC", "Tractor Sazi")),
        ("吉达国民", 2530, ("Al Ahli", "Al-Ahli", "Al Ahli Saudi FC")),
        ("塔什干棉农", 102141, ("Pakhtakor Tashkent", "Pakhtakor")),
        ("卡迪西亚", 101919, ("Al Qadsiah", "Al-Qadsiah", "Al-Qadisiyah")),
        ("华斯尔", 102111, ("Al-Wasl", "Al Wasl", "迪拜祈祷", "迪拜连接")),
        ("德黑兰独立", 101614, ("Esteghlal", "Esteghlal FC")),
        ("萨德", 101895, ("Al-Sadd", "Al Sadd", "Al Sadd SC")),
        ("艾因", 102117, ("Al-Ain", "Al Ain", "Al Ain FC")),
        ("利雅得胜利", 101918, ("Al Nassr FC", "Al-Nassr", "Al Nassr")),
        ("利雅得新月", 2529, ("Al Hilal", "Al-Hilal", "Al Hilal SFC")),
        ("加拉法", 101897, ("Al-Gharafa", "Al Gharafa", "Al Gharafa SC")),
        ("大田韩亚市民", 133900, ("Daejeon Hana Citizen", "Daejeon Citizen", "大田市民")),
        ("京都不死鸟", 8542, ("Kyoto Sanga FC", "Kyoto Sanga")),
        ("大阪钢巴", 6582, ("Gamba Osaka",)),
        ("河内公安", 614354, ("Công An Hà Nội", "Cong An Ha Noi", "Hanoi Police")),
        ("鹿岛鹿角", 4397, ("Kashima Antlers",)),
        ("纽卡斯尔喷气机", 6454, ("Newcastle Jets", "Newcastle Jets FC")),
        ("拉查武里", 421346, ("Ratchaburi FC", "Ratchaburi")),
        ("上海海港", 198616, ("Shanghai Port", "Shanghai Port FC", "上海上港")),
        ("北京国安", 4177, ("Beijing Guoan", "Beijing Guoan FC")),
        ("浦项制铁", 109373, ("Pohang Steelers",)),
        ("柔佛新山", 165228, ("Johor Darul Ta'zim", "Johor Darul Tazim", "JDT", "柔佛")),
        ("武里南联", 165243, ("Buriram United",)),
        ("全北现代", 46038, ("Jeonbuk Hyundai Motors FC", "Jeonbuk Hyundai Motors", "全北现代汽车")),
        ("柏太阳神", 8699, ("Kashiwa Reysol",)),
        ("泰港", 165255, ("Port FC", "Port MTI FC")),
        ("神户胜利船", 4688, ("Vissel Kobe",)),
    ),
    "亚冠二级": (
        ("戈尔戈哈尔", 389880, ("Gol Gohar", "Gol Gohar Sirjan")),
        ("阿布扎比半岛", 102101, ("Al-Jazira", "Al Jazira", "Al Jazira Club")),
        ("阿卡达格", 1689659, ("Arkadag", "Arkadag FK")),
        ("慕哈瑞克", 101598, ("Muharraq", "Al-Muharraq", "Al Muharraq")),
        ("阿布扎比统一", 102122, ("Al-Wahda", "Al Wahda", "Al Wahda FC")),
        ("科威特竞技", 101713, ("Kuwait SC", "Kuwait Sports Club")),
        ("哈尔迪亚", 1288463, ("Al Khalidiyah", "Al-Khaldiya", "Khalidiya")),
        ("纳萨夫", 102153, ("Nasaf Qarshi", "Nasaf", "FC Nasaf")),
        ("纳达", 101748, ("Al-Nahda", "Al Nahda", "Al-Nahda Club")),
        ("布赖代合作", 205686, ("Al-Taawoun", "Al Taawoun", "Al-Taawoun FC")),
        ("赖扬", 101898, ("Al-Rayyan", "Al Rayyan", "Al Rayyan SC")),
        ("费萨里", 101665, ("Al-Faisaly", "Al Faisaly", "Al-Faisaly SC")),
        ("侯赛因", 101688, ("Al-Hussein SC", "Al Hussein", "Al-Hussein Irbid")),
        ("东孟加拉", 165184, ("East Bengal FC", "East Bengal")),
        ("巴格达警察", 101655, ("Al Shorta", "Al-Shorta", "Al Shorta SC")),
        ("锡卜", 101759, ("Al-Seeb", "Al Seeb", "Al-Seeb Club")),
        ("首尔FC", 92630, ("FC Seoul", "Seoul FC")),
        ("万隆", 165196, ("Persib Bandung", "Persib")),
        ("越电信", 743070, ("Viettel", "The Cong - Viettel FC", "Thể Công-Viettel")),
        ("墨尔本胜利", 6230, ("Melbourne Victory", "Melbourne Victory FC")),
        ("狮城水手", 67366, ("Lion City Sailors FC", "Lion City Sailors")),
        ("巴吞联", 165250, ("BG Pathum United", "BG Pathum United FC")),
        ("阿德莱德联", 8008, ("Adelaide United", "Adelaide United FC")),
        ("大埔", 165169, ("Tai Po", "Tai Po FC", "Wofoo Tai Po")),
        ("町田泽维亚", 194011, ("Machida Zelvia", "FC Machida Zelvia")),
        ("柴桢", 542025, ("Svay Rieng", "Preah Khan Reach Svay Rieng")),
        ("上海申花", 6628, ("Shanghai Shenhua", "Shanghai Shenhua FC")),
        ("淡滨尼流浪者", 67386, ("Tampines Rovers FC", "Tampines Rovers")),
        ("杰志", 165165, ("Kitchee", "Kitchee SC")),
        ("江原FC", 164734, ("Gangwon FC", "Gangwon")),
        ("金边皇冠", 202520, ("Phnom Penh", "Phnom Penh Crown", "Phnom Penh Crown FC")),
        ("古晋城", 1114226, ("Kuching City", "Kuching City FC")),
    ),
}


# Verified identities needed outside the fully enumerated league rosters above.
# Keeping these separate avoids presenting a partial cup or national-team list
# as a complete competition roster while still providing safe provider-ID
# matching and a direct team-history fallback when FotMob omits the fixture.
SUPPLEMENTAL_TEAM_ROWS: tuple[tuple[str, int, tuple[str, ...]], ...] = (
    ("吉达国民", 2530, ("Al Ahli", "Al-Ahli", "Al Ahli Saudi FC")),
    ("塔什干棉农", 102141, ("Pakhtakor Tashkent", "Pakhtakor")),
    ("博德闪耀", 8402, ("Bodø/Glimt", "Bodo/Glimt", "Bodo Glimt", "博德")),
    ("桑德菲杰", 8609, ("Sandefjord", "Sandefjord Fotball")),
    ("中国女足", 5904, ("China (W)", "China Women")),
    ("中国香港女足", 623229, ("Hong Kong (W)", "Hong Kong Women")),
)


_ALL_TEAM_ROWS = (
    *(row for rows in LEAGUE_TEAM_ROWS.values() for row in rows),
    *(row for rows in EUROPEAN_CUP_TEAM_ROWS.values() for row in rows),
    *(row for rows in ASIAN_CUP_TEAM_ROWS.values() for row in rows),
    *SUPPLEMENTAL_TEAM_ROWS,
)


LEAGUE_TEAM_ALIASES: dict[str, tuple[str, ...]] = {}
FOTMOB_TEAM_IDS: dict[str, str] = {}
for _local_name, _team_id, _aliases in _ALL_TEAM_ROWS:
    _existing_id = FOTMOB_TEAM_IDS.get(_local_name)
    if _existing_id is not None and _existing_id != str(_team_id):
        raise ValueError(f"Conflicting FotMob IDs for {_local_name}: {_existing_id} vs {_team_id}")
    FOTMOB_TEAM_IDS[_local_name] = str(_team_id)
    _merged_aliases = list(LEAGUE_TEAM_ALIASES.get(_local_name, ()))
    for _alias in _aliases:
        if _alias not in _merged_aliases:
            _merged_aliases.append(_alias)
    LEAGUE_TEAM_ALIASES[_local_name] = tuple(_merged_aliases)

LEAGUE_TEAM_COUNTS: dict[str, int] = {
    league: len(rows) for league, rows in LEAGUE_TEAM_ROWS.items()
}

EUROPEAN_CUP_TEAM_COUNTS: dict[str, int] = {
    competition: len(rows) for competition, rows in EUROPEAN_CUP_TEAM_ROWS.items()
}

ASIAN_CUP_TEAM_COUNTS: dict[str, int] = {
    competition: len(rows) for competition, rows in ASIAN_CUP_TEAM_ROWS.items()
}
